### ISSUE TITLE
betterDefine cannot resolve TS from file paths beginning with "@"

### ISSUE THREAD

**Issue by richardtallent-erm** [sxzz/unplugin-vue-macros#139]
### Describe the bug

This import works:

```
import type { IFieldEmits } from "../../my-component-lib/src/forms/FieldProps"
```

This import does not work, even though it resolves to the same folder:

```
import type { IFieldEmits } from "@/my-component-lib/src/forms/FieldProps"
```

The error I receive is:

```
5:48:41 PM [vite] warning: unplugin-vue-better-define SyntaxError: Cannot resolve TS definition.
  Plugin: unplugin-vue-better-define
  File: C:/MyProjectPath/src/forms/FieldInput.vue
SyntaxError: Cannot resolve TS definition.
    at resolveDefinitions (C:\MyProjectPath\node_modules\@vue-macros\api\dist\index.js:459:13)
    at async handleTSEmitsDefinition (C:\MyProjectPath\node_modules\@vue-macros\api\dist\index.js:389:43)
    at async processDefineEmits (C:\MyProjectPath\node_modules\@vue-macros\api\dist\index.js:622:15)
    at async analyzeSFC (C:\MyProjectPath\node_modules\@vue-macros\api\dist\index.js:548:9)
    at async transformBetterDefine (C:\MyProjectPath\node_modules\@vue-macros\better-define\dist\chunk-7CI72ON6.js:17:18)
    at async TransformContext.transform (C:\MyProjectPath\node_modules\@vue-macros\better-define\dist\chunk-7CI72ON6.js:99:16)
    at async Object.transform (file:///C:/MyProjectPath/node_modules/vite/dist/node/chunks/dep-c842e491.js:41421:30)
    at async loadAndTransform (file:///C:/MyProjectPath/node_modules/vite/dist/node/chunks/dep-c842e491.js:37808:29)
```

It appears (so far) that I can use the "@" syntax just fine for the `defineProps` types or their base types, just not for `defineEmits`. ("@" is mapped to the project root in my `tsconfig.json`, not to "/src".)

Thanks for writing this plugin!

### Reproduction

https://github.com/richardtallent

### System Info

```Shell
I can provide a reproduction next week if needed, but I'm shutting down my work laptop for the weekend and wanted to get this issue filed beforehand.

 System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 17.01 GB / 31.73 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.26)  
    Internet Explorer: 11.0.19041.1566

Also:
- vue 3.2.41
- vite 3.2.2
- unplugin-vue-macros 0.16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed, please try the latest version.

**Comment by richardtallent-erm** [comment]
Thanks, this worked!
