### ISSUE TITLE
[betterDefine] Warning when resolving type from .d.ts file in package

### ISSUE THREAD

**Issue by killjoy1221** [sxzz/unplugin-vue-macros#202]
### Describe the bug

A warning appears whenever a type from another package's .d.ts file is used as a prop type. In my example, I used `KebabCase` from [`type-fest`](https://www.npmjs.com/package/type-fest). The warning is also shown when used as the event name in `defineEmits()`

```
6:59:15 PM [vite] warning: unplugin-vue-better-define Error: Failed to resolve entry for package "type-fest". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: unplugin-vue-better-define
  File: /home/matthewm/vue-macros-better-define-dts/src/components/TestComponent.vue
Error: Failed to resolve entry for package "type-fest". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///home/matthewm/vue-macros-better-define-dts/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21837:11)
    at resolvePackageEntry (file:///home/matthewm/vue-macros-better-define-dts/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21834:5)
    at tryNodeResolve (file:///home/matthewm/vue-macros-better-define-dts/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21572:20)
    at Context.resolveId (file:///home/matthewm/vue-macros-better-define-dts/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:21336:28)
    at async Object.resolveId (file:///home/matthewm/vue-macros-better-define-dts/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41433:32)
    at async Context.resolve (file:///home/matthewm/vue-macros-better-define-dts/node_modules/.pnpm/vite@4.0.4/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41180:23)
    at async tryResolve (file:///home/matthewm/vue-macros-better-define-dts/node_modules/.pnpm/@vue-macros+better-define@1.1.3_vue@3.2.45/node_modules/@vue-macros/better-define/dist/chunk-BDVRF63H.mjs:105:22)
    at async resolveFn (file:///home/matthewm/vue-macros-better-define-dts/node_modules/.pnpm/@vue-macros+better-define@1.1.3_vue@3.2.45/node_modules/@vue-macros/better-define/dist/chunk-BDVRF63H.mjs:107:34)
    at async resolveTSReferencedType (file:///home/matthewm/vue-macros-better-define-dts/node_modules/.pnpm/@vue-macros+api@0.2.3_vue@3.2.45/node_modules/@vue-macros/api/dist/chunk-66XTHNXL.mjs:172:24)
    at async resolveTSExports (file:///home/matthewm/vue-macros-better-define-dts/node_modules/.pnpm/@vue-macros+api@0.2.3_vue@3.2.45/node_modules/@vue-macros/api/dist/chunk-66XTHNXL.mjs:283:35)
```

### Reproduction

https://github.com/killjoy1221/vue-macros-better-define-dts

### System Info

```Shell
System:
    OS: Linux 6.0 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 21.17 GB / 31.22 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
It's just a warning. We can ignore it now.

But `betterDefine` currently doesn't support complex types (all types from `type-fest`).

For props, you can use it on prop's type, but NOT key
```ts
interface Props {
  message: PhraseTypes // ✅
  [PhraseTypes]: string // ❌
}
```

For events, you can't use it on the first param (aka event's name)
```ts
interface Emits {
  (event: 'something', value: PhraseTypes): void // ✅
  (event: PhraseTypes): void // ❌
}
```

**Comment by killjoy1221** [comment]
That is how I'm using it for props. I should also note that this works perfectly fine with vanilla vue since Props is defined inside the setup.

**Comment by sxzz** [comment]
@killjoy1221 Yes, the props definition in your project works. The only difference using Vue Macros is that there's one warning message in the terminal. I'll try to fix that.

But for emits, you cannot define them as in your project, whatever in vanilla Vue or Vue Macros.
