### ISSUE TITLE
Can't import from vue file (Nuxt)

### ISSUE THREAD

**Issue by f3oall** [sxzz/unplugin-vue-macros#208]
### Describe the bug

When I import interface from vue file, I got error:
```
warning: unplugin-vue-better-define SyntaxError: Unexpected token, expected "}" (3:7)
  Plugin: unplugin-vue-better-define
  File: /home/f3oall/coding/js/nuxt/examples/a.vue
                                                                      11:34:33

 WARN  Unexpected token, expected "}" (3:7)                           11:34:35

  at instantiate (node_modules/@babel/parser/lib/index.js:67:32)
  at constructor (node_modules/@babel/parser/lib/index.js:364:12)
  at JSXParserMixin.raise (node_modules/@babel/parser/lib/index.js:3363:19)
  at JSXParserMixin.unexpected (node_modules/@babel/parser/lib/index.js:3396:16)
  at JSXParserMixin.expect (node_modules/@babel/parser/lib/index.js:3758:28)
  at JSXParserMixin.jsxParseExpressionContainer (node_modules/@babel/parser/lib/index.js:7095:10)
  at JSXParserMixin.jsxParseElementAt (node_modules/@babel/parser/lib/index.js:7173:36)
  at JSXParserMixin.jsxParseElement (node_modules/@babel/parser/lib/index.js:7218:17)
  at JSXParserMixin.parseExprAtom (node_modules/@babel/parser/lib/index.js:7231:19)
  at JSXParserMixin.parseExprSubscripts (node_modules/@babel/parser/lib/index.js:11182:23)
```

Import from .ts works as expected. If it's not a bug, I suggest extending the docs, because it's not clear that you can't import from .vue files.

### Reproduction

https://github.com/f3oall/vue-macto-reproduction

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 3.99 GB / 7.62 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 19.2.0 - ~/.nvm/versions/node/v19.2.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v19.2.0/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Not supported for importing from Vue SFC file yet. We'll support it in the future!
