### ISSUE TITLE
defineProps crashes volar

### ISSUE THREAD

**Issue by killjoy1221** [sxzz/unplugin-vue-macros#220]
### Describe the bug

When the `@vue-macros/volar/define-props` plugin is enabled, Volar crashes with the following error.

```
[Error - 11:20:29 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read properties of undefined (reading 'defineProps')
  Code: -32603 
$PWD/node_modules/.pnpm/@vue-macros+volar@0.5.15_vue@3.2.45/node_modules/@vue-macros/volar/dist/define-props.js:3
  vueCompilerOptions.macros.defineProps.push("$defineProps");
                            ^

TypeError: Cannot read properties of undefined (reading 'defineProps')
    at plugin ($PWD/node_modules/.pnpm/@vue-macros+volar@0.5.15_vue@3.2.45/node_modules/@vue-macros/volar/dist/define-props.js:3:29)
    at $HOME/.vscode-server/extensions/vue.volar-1.0.20-linux-x64/dist/node/server.js:888:10271
    at Array.map (<anonymous>)
    at qOe ($HOME/.vscode-server/extensions/vue.volar-1.0.20-linux-x64/dist/node/server.js:888:10264)
    at Object.WOe ($HOME/.vscode-server/extensions/vue.volar-1.0.20-linux-x64/dist/node/server.js:1017:300)
    at Object.getLanguageModules ($HOME/.vscode-server/extensions/vue.volar-1.0.20-linux-x64/dist/node/server.js:1132:8460)
    at $HOME/.vscode-server/extensions/vue.volar-1.0.20-linux-x64/dist/node/server.js:495:1068
    at Array.map (<anonymous>)
    at Object.f [as getLanguageService] ($HOME/.vscode-server/extensions/vue.volar-1.0.20-linux-x64/dist/node/server.js:495:990)
    at $HOME/.vscode-server/extensions/vue.volar-1.0.20-linux-x64/dist/node/server.js:495:15810
[Info  - 11:20:29 AM] Connection to server got closed. Server will restart.
```

This appears to only effect remote ssh workspaces. Local and WSL workspaces seems to work fine. I have not tested it with a container workspace.

I am however able to work around it by adding this to `vueCompilerOptions`.
```json
{
  "vueCompilerOptions": {
    "macros": {
      "defineProps": []
    }
  }
}
```

### Reproduction

N/A

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
    Memory: 11.51 GB / 15.63 GB
    Container: Yes
    Shell: 6.21.00 - /bin/csh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 9.3.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
it requires the latest volar. Please upgrade your vue-tsc and vscode extension to `1.0.24`.
