### ISSUE TITLE
betterDefine does not work with Quasar prop interfaces

### ISSUE THREAD

**Issue by geewizz246** [sxzz/unplugin-vue-macros#278]
### Describe the bug

Using the `betterDefine` feature with Quasar's component prop typescript interfaces does not work.
```vue
<script setup lang="ts">
import type { QInputProps } from 'quasar';

defineProps<QInputProps>();
</script>

<template>
  <QInput v-bind="$props">
    <template #before> @ </template>
  </QInput>
</template>

```
 I keep getting an error from vite when I try do this.
 
 ```
[vite] Internal server error: [@vue/compiler-sfc] type argument passed to defineProps() must be a literal type, or a reference to an interface or literal type.

/home/projects/vitejs-vite-mefbzk/src/components/MyInput.vue
2  |  import type { QInputProps } from 'quasar';
3  |  
4  |  defineProps<QInputProps>();
   |              ^^^^^^^^^^^
5  |  </script>
6  |  
  Plugin: vite:vue
  File: /home/projects/vitejs-vite-mefbzk/src/components/MyInput.vue
      at error (file:///home/projects/vitejs-vite-mefbzk/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3601:15)
      at processDefineProps (file:///home/projects/vitejs-vite-mefbzk/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3658:17)
      at Object.compileScript (file:///home/projects/vitejs-vite-mefbzk/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:4200:17)
      at resolveScript (file://file:///home/projects/vitejs-vite-mefbzk/node_modules/@vitejs/plugin-vue/dist/index.mjs:284:31)
      at genScriptCode (file://file:///home/projects/vitejs-vite-mefbzk/node_modules/@vitejs/plugin-vue/dist/index.mjs:2415:18)
      at transformMain (file://file:///home/projects/vitejs-vite-mefbzk/node_modules/@vitejs/plugin-vue/dist/index.mjs:2231:54)
      at TransformContext.transform (file://file:///home/projects/vitejs-vite-mefbzk/node_modules/@vitejs/plugin-vue/dist/index.mjs:2714:16)
      at Object.transform (file://file:///home/projects/vitejs-vite-mefbzk/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41722:44)
      at async loadAndTransform (file://file:///home/projects/vitejs-vite-mefbzk/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:39527:29)
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-mefbzk?terminal=dev

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.54 GB / 15.88 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lee1994522** [comment]
I have met the same problem, any solution?
