### ISSUE TITLE
 warning: unplugin-vue-better-define SyntaxError: Cannot resolve TS definition.

### ISSUE THREAD

**Issue by keymasroy** [sxzz/unplugin-vue-macros#298]
### Describe the bug

I made component with interface type as below code for reference in other component
```html
<template>
  <slot :modelValue="modelValue" :onUpdate:modelValue="value => (modelValue = value)" :loadZipContainer="loadZipContainer">
    <UPopup v-model="modelValue" :width="800" :height="600" title="Search" @shown="() => loadZipContainer()">
      <div ref="zipContianerEl" style="width: 100%; height: 100%"></div>
    </UPopup>
  </slot>
</template>
<script lang="ts" setup>
import { useHead } from '#app'
import { ref, withDefaults, defineEmits, defineProps } from '#ustra/nuxt'
import { useVModel } from '@vueuse/core'
import toNumber from 'lodash/toNumber'
import UPopup from '../dialog/u-popup.vue'
import { openDaumPostScreen, DaumPostResult, DaumPostScreenOptions } from '#ustra/nuxt/externals/daum/post'

const props = withDefaults(defineProps<Props>(), {
  options: () => {
    return {}
  },
  addLatLng: false,
  apiKey: () => {
    return $ustra.components.getComponentsOption('UDaumPostPopup').apiKey
  },
})
const emits = defineEmits<Emits>()

const zipContianerEl = ref<HTMLDivElement>()
const { modelValue, loadZipContainer, getLoadScripts } = useDaumPostPopup({
  zipContianerEl,
  emits,
  props,
})

useHead({
  script: getLoadScripts(),
})
</script>
<script lang="ts">
import { Ref } from '#ustra/nuxt'

export interface Props {

  modelValue: boolean

  options?: DaumPostScreenOptions

  addLatLng?: boolean

  apiKey?: string
}

export interface Emits {
  (e: 'selected', data: DaumPostResult): void
  (e: 'update:modelValue', value: boolean): void
}

export const useDaumPostPopup = (options: {

  props: Props

  emits: Emits

  zipContianerEl?: Ref<HTMLElement>


  convertResultHandler?: (result: DaumPostResult) => DaumPostResult
}) => {
  if (options.props.addLatLng && !options.props.apiKey) {
    throw new Error('not found api key')
  }

  const modelValue = useVModel(options.props, 'modelValue')

  function convertResult(result: DaumPostResult) {
    if (options.convertResultHandler) {
      return options.convertResultHandler(result)
    }

    return result
  }

  function loadZipContainer(zipContianerEl?: HTMLElement) {
    if (zipContianerEl) {
      options.zipContianerEl = ref(zipContianerEl)
    }

    $ustra.utils.core
      .getObjectAsync(() => options.zipContianerEl.value)
      .then(zipContianerEl => {
        openDaumPostScreen(zipContianerEl, {
          ...options.props.options,
          onSelected(data) {
            if (options.props.addLatLng) {
              $ustra.global.kakao.maps.load(() => {
                const geocoder = new $ustra.global.kakao.maps.services.Geocoder()

                geocoder.addressSearch(data.address, (results, status) => {
                  if (status === $ustra.global.kakao.maps.services.Status.OK && results.length > 0) {
                    data.lat = toNumber(results[0].x)
                    data.lng = toNumber(results[0].y)
                    options.emits('selected', convertResult(data))
                    modelValue.value = false
                    return
                  }

                  options.emits('selected', convertResult(data))
                  modelValue.value = false
                  return
                })
              })

              return
            }

            options.emits('selected', convertResult(data))
            modelValue.value = false
          },
        })
      })
  }

  function getLoadScripts() {
    const scripts = [{ key: 'daumPostMapScript', src: '//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js' }]
    if (options.props.addLatLng) {
      scripts.push({ key: 'kakaoMapScript', src: `//dapi.kakao.com/v2/maps/sdk.js?autoload=false&appkey=${options.props.apiKey}&libraries=services` })
    }

    return scripts
  }

  return { modelValue, loadZipContainer, getLoadScripts }
}

export default {
  name: 'UDaumPostPopup',
}
</script>

```

The code is declared types in script and declare action for template in setup script.
I wonder why show warning message.

```text
[vite] warning: unplugin-vue-better-define SyntaxError: Cannot resolve TS definition.                                                      13:21:25  
  Plugin: unplugin-vue-better-define
  File: C:/ustra/workspace/project/hcorestore/node/fo/node_modules/@ustra/nuxt-vuetify/src/components/daum/u-daum-post-popup.vue


 WARN  Cannot resolve TS definition.                                                                                                                           13:21:25  

  at resolveDefinitions (node_modules\@vue-macros\api\dist\index.js:441:13)
  at async handleTSPropsDefinition (node_modules\@vue-macros\api\dist\index.js:179:43)
  at async processDefineProps (node_modules\@vue-macros\api\dist\index.js:698:15)
  at async processWithDefaults (node_modules\@vue-macros\api\dist\index.js:727:27)
  at async analyzeSFC (node_modules\@vue-macros\api\dist\index.js:669:9)
  at async transformBetterDefine (node_modules\@vue-macros\better-define\dist\chunk-NQKGHLJQ.js:19:18)
  at async TransformContext.transform (node_modules\@vue-macros\better-define\dist\chunk-NQKGHLJQ.js:154:18)
  at async Object.transform (/C:/ustra/workspace/project/hcorestore/node/fo/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
  at async loadAndTransform (/C:/ustra/workspace/project/hcorestore/node/fo/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
```

Here is my environment
- nuxt 3.2.3
- vue 3.2.47
- unplugin-vue-define-options 1.2.3
- 

### Reproduction

Nothing

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   
    Memory: 12.24 GB / 31.76 GB
  Binaries:
    Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Try to move `export interface Props` to `<script setup>` block.

**Comment by keymasroy** [comment]
Oh! Thanks. It is my mistake.
I read your guide, again (https://vue-macros.sxzz.moe/features/export-props.html)

**Comment by wenfangdu** [comment]
> Try to move `export interface Props` to `<script setup>` block.

@sxzz Isn't this against the guideline?

![image](https://user-images.githubusercontent.com/28700378/226304700-fd758755-61ec-4cad-9177-69a34ad13114.png)

[Usage alongside normal `<script>​`.](https://vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script)

[Johnson suggests I move `export type ...` to a separate `<script>`](https://github.com/vuejs/language-tools/issues/2457#issuecomment-1475465785), and you're suggesting the opposite 😵😵😵.

**Comment by wenfangdu** [comment]
@sxzz And I even raised a bug report [here](https://github.com/vuejs/eslint-plugin-vue/issues/2108).

**Comment by sxzz** [comment]
@wenfangdu `export type` is not actually a real export.

Even though Volar suggests that put `export type` to the normal script block. But I (this project) am working to avoid multiple script blocks, which means this project hopes developers to use one `<script setup>` only.

**Comment by sxzz** [comment]
Or you can export types in a normal TS file and import them in the Vue SFC.

**Comment by wenfangdu** [comment]
> @wenfangdu `export type` is not actually a real export.
> 
> Even though Volar suggests that put `export type` to the normal script block. But I (this project) am working to avoid multiple script blocks, which means this project hopes developers to use one `<script setup>` only.

@sxzz How do you declare real named exports in `<script setup>`?

**Comment by sxzz** [comment]
I mean, exporting a type is not a real runtime code. It's only a TS type.

For runtime exports (`export const foo = bar`), we cannot export them in `<script setup>`, so currently we have to put them on the normal setup block.

This case is pretty complex for betterDefine, so finally, I will suggest developers extract types into a normal TS file and import them in the Vue SFC file.
